version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      POSTGRES_USER: user
    ports:
      - "${DOCKER_DB_EXPOSED_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  java:
    build: ./java
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
